### ISSUE TITLE
Save method adds backslash

### ISSUE THREAD

**Issue by ravichandranjv** [elshor/dstools#2]
The save method called on the Collection as below

`movies = ds.Collection()
    .loadCSV('.....tmdb_5000_credits.csv');
movies.save('....tmdb-credits.json');`

adds '\\' to the saved JSON result. 

This happens from both the Jupyter Javascript notebook and from node.js app using dstools. 

Is it normal behavior?

Sample output below:

[{"movie_id":19995,"title":"Avatar","cast":"[{\"cast_id\": 242, \"character\": \"Jake Sully\", \"credit_id\": \"5602a8a7c3a3685532001c9a\",

**Comment by ravichandranjv** [comment]
Resolved by the .stringify(..).replace method on the string. When I opened the issue, I wasn't able to browse/open the JSON file as it was too large and the browser and the IDEs were crashing continuously so wasn't sure how many illegal characters would be in the string.  Only the '\\' seems to be the addition.

Attached the screenhot before flushing out the backslashes and after for future reference.
![image](https://user-images.githubusercontent.com/804860/40689355-6961ad20-63bf-11e8-867b-a55c24400cfe.png)

**Comment by elshor** [comment]
I want to make sure I understand the issue. In the sample output you sent I
don't see any "\'". What there just a problem in understanding the output?

**Comment by ravichandranjv** [comment]
@elshor Thanks for responding. 

Please tag your response with my github usename - @ravichandranjv - so that I could get the notification for timely response. 

The below image shows the code used for the previous post. I used the save method to save the converted .csv file into JSON but found the backslash-es in the JSON so I thought that it must be dstools doing the insertions.

![image](https://user-images.githubusercontent.com/804860/40818331-4ac4bcd4-6574-11e8-84fd-031b39d24f55.png)

I closed the issue because I found that using JSON.stringify, I could remove all the backslash-es and the JSON would become legal data as there were no other illegal characters in the string but it seems that the backslash-es are neither in the .csv file nor in the mongodb collection that I later imported the .csv file into - without using `dstools`.  

Please take a look at the highlighted part of the below screenshot. The response contains backslash-es. 

![image](https://user-images.githubusercontent.com/804860/40818239-d83efbe8-6573-11e8-99aa-3746c57ec1c3.png)

So, it is clear now that the dstools methods are not adding the backslash-es but where could the backslash-es be originating from, if the console's log does not contain the backslash-es?

PS: @elshor Although this does not seem like a dstools issue now, the question may not be so relevant but if you do have an idea, please do let me know and thanks for a great package!
