### ISSUE TITLE
documentation not clear enough 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [elshor/dstools#3]
Hi, 

I'm using dstools for datascience. It says that some method would return collection. I don't get understand what type of collection it is. If I try to print the collection. 

Why can't I get things. I only want to get columns who are female 'F' sex. How do I do that? I'm really confused right now. 

<img width="1114" alt="screen shot 2018-09-01 at 11 45 26 pm" src="https://user-images.githubusercontent.com/8083613/44948771-3e87e200-ae41-11e8-94e4-b61fa040de30.png">

I'm using this dataset 

https://www.kaggle.com/open-powerlifting/powerlifting-database

**Comment by elshor** [comment]
You need to use the filterEqual function like this:
```
males = powerliftingdata.filterEqual('Sex','M');
//count males
males.count();//299045
```

**Comment by AbhimanyuAryan** [comment]
@elshor is there any way to handle missing data with dstools same as pandas in python?

**Comment by elshor** [comment]
There is no special handling of missing data. What behavior would you
expect?

**Comment by AbhimanyuAryan** [comment]
@elshor can I get your email. I need to discuss something very important

**Comment by AbhimanyuAryan** [comment]
I'm planning to reimplement this library but in a more robust way & I need your help

**Comment by AbhimanyuAryan** [comment]
I haven't committed anything yet. But I'm trying to build a replacement for pandas library that Python guys have: https://github.com/AbhimanyuAryan/pandas-ts

**Comment by AbhimanyuAryan** [comment]
when we look at a data analysis tool we need something as robust as pandas in Javascript/TypeScript 

https://github.com/pandas-dev/pandas

Atleast these features should be supported: 

Here are just a few of the things that pandas does well:

```
    * Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
    * Size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects
    * Automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let Series, DataFrame, etc. automatically align the data for you in computations
    * Powerful, flexible group by functionality to perform split-apply-combine operations on data sets, for both aggregating and transforming data
    * Make it easy to convert ragged, differently-indexed data in other Python and NumPy data structures into DataFrame objects
    * Intelligent label-based slicing, fancy indexing, and subsetting of large data sets
    * Intuitive merging and joining data sets
    *  Flexible reshaping and pivoting of data sets
    *  Hierarchical labeling of axes (possible to have multiple labels per tick)
    * Robust IO tools for loading data from flat files (CSV and delimited), Excel files, databases, and saving/loading data from the ultrafast HDF5 format
    * Time series-specific functionality: date range generation and frequency conversion, moving window statistics, moving window linear regressions, date shifting and lagging, etc.


```

**Comment by elshor** [comment]
Replied on twitter
